# 机器学习基础

## numpy基础

随机生成一个4X4的矩阵，以及求逆操作

In [5]:
from numpy import *
randMat = mat(random.rand(4, 4))
print(randMat)

[[0.53024099 0.0507495  0.55549901 0.7802177 ]
 [0.72919775 0.66158637 0.87937919 0.84501668]
 [0.45086298 0.19613448 0.67742387 0.29474226]
 [0.66020267 0.43687826 0.71760591 0.43100195]]


In [6]:
print(randMat.I)

[[ 1.47994715 -3.50594011 -4.01290544  6.9388775 ]
 [-1.73011728  2.03655284 -1.13576079 -0.08421375]
 [-0.94618241  1.10791985  4.71891224 -3.68639948]
 [ 1.0621104   1.46137512 -0.55869641 -2.08558742]]


输出与对角矩阵的误差

In [8]:
invrandMat = randMat.I
myEye = randMat * invrandMat
print (myEye - eye(4))

[[ 0.00000000e+00 -4.44089210e-16 -1.11022302e-16  0.00000000e+00]
 [-1.11022302e-16 -1.11022302e-16  2.22044605e-16  2.22044605e-16]
 [-5.55111512e-17 -5.55111512e-17 -1.11022302e-16  1.11022302e-16]
 [-3.33066907e-16 -5.55111512e-16  3.60822483e-16  6.66133815e-16]]
